<# Hash-gated registration of the governed LOS user-provisioning host and its two unbound Custom APIs. #>
[CmdletBinding()]
param(
  [switch]$Apply,[switch]$Force,[string]$ExpectedAssemblySha256,[string]$ExpectedManifestSha256,
  [string]$AssemblyPath='dataverse-plugins\CommercialLendingLOS.Plugins\bin\Release\net462\CommercialLendingLOS.Plugins.dll',
  [string]$ManifestPath='dataverse-plugins\CommercialLendingLOS.Plugins\LosUserProvisioningCustomApiRegistration.json'
)
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;$dll=(Resolve-Path (Join-Path $repo $AssemblyPath)).Path;$manifestFile=(Resolve-Path (Join-Path $repo $ManifestPath)).Path
$dllHash=(Get-FileHash -Algorithm SHA256 -LiteralPath $dll).Hash.ToLowerInvariant();$manifestHash=(Get-FileHash -Algorithm SHA256 -LiteralPath $manifestFile).Hash.ToLowerInvariant();$manifest=Get-Content -Raw $manifestFile|ConvertFrom-Json
if($Apply-and($dllHash-ne$ExpectedAssemblySha256.Trim().ToLowerInvariant()-or$manifestHash-ne$ExpectedManifestSha256.Trim().ToLowerInvariant())){throw 'Artifact hash mismatch.'}
Write-Host("Mode={0} assemblySha256={1} manifestSha256={2}"-f$(if($Apply){'APPLY'}else{'DRY_RUN'}),$dllHash,$manifestHash);if(-not$Apply){Write-Host 'NO MUTATION: registration package validated.';exit 0}
$orgUrl='https://org8c12c949.crm.dynamics.com';if(-not$Force){throw 'Apply requires -Force after the hash-gated dry run.'};$token=(Get-AzAccessToken -ResourceUrl $orgUrl).Token;if($token-is[Security.SecureString]){$token=[Net.NetworkCredential]::new('',$token).Password};if(-not$token){throw 'Dataverse authentication failed.'}
$api="$orgUrl/api/data/v9.2";$headers=@{Authorization="Bearer $token";'OData-MaxVersion'='4.0';'OData-Version'='4.0';Accept='application/json';'Content-Type'='application/json';Prefer='return=representation'}
function Esc([string]$v){$v.Replace("'","''")};function Rows([string]$path){@((Invoke-RestMethod Get "$api/$path" -Headers $headers).value)};function One($r,[string]$l){if(@($r).Count-ne 1){throw"Expected one $l; found $(@($r).Count)."};@($r)[0]};function Post([string]$s,[hashtable]$b){Invoke-RestMethod Post "$api/$s" -Headers $headers -Body($b|ConvertTo-Json -Depth 12)};function Patch([string]$s,[string]$id,[hashtable]$b){Invoke-RestMethod Patch "$api/$s($id)" -Headers $headers -Body($b|ConvertTo-Json -Depth 12)|Out-Null}
try{
  $bytes=[IO.File]::ReadAllBytes($dll);$an=[Reflection.AssemblyName]::GetAssemblyName($dll);$pkt=($an.GetPublicKeyToken()|%{$_.ToString('x2')})-join'';if(-not$pkt){throw'Assembly must be strong-name signed.'}
  $ar=Rows "pluginassemblies?`$select=pluginassemblyid&`$filter=name eq '$(Esc $manifest.assemblyName)'";$ab=@{name=$manifest.assemblyName;content=[Convert]::ToBase64String($bytes);isolationmode=2;sourcetype=0;version=$an.Version.ToString();culture='';publickeytoken=$pkt};if($ar.Count-eq0){$aid=[string](Post pluginassemblies $ab).pluginassemblyid}else{$aid=[string](One $ar 'plugin assembly').pluginassemblyid;Patch pluginassemblies $aid $ab}
  $tr=Rows "plugintypes?`$select=plugintypeid&`$filter=typename eq '$(Esc $manifest.pluginType)'";if($tr.Count-eq0){$tid=[string](Post plugintypes @{typename=$manifest.pluginType;name='LosUserProvisioningCustomApiPlugin';friendlyname='LosUserProvisioningCustomApiPlugin';'pluginassemblyid@odata.bind'="/pluginassemblies($aid)"}).plugintypeid}else{$tid=[string](One $tr 'plugin type').plugintypeid}
  foreach($spec in @($manifest.apis)){
    $rows=Rows "customapis?`$select=customapiid&`$filter=uniquename eq '$(Esc $spec.uniqueName)'";$body=@{uniquename=$spec.uniqueName;name=$spec.uniqueName;displayname=$spec.displayName;description=$spec.description;bindingtype=0;allowedcustomprocessingsteptype=0;isfunction=$false;isprivate=$false;executeprivilegename=$spec.executePrivilegeName;'PluginTypeId@odata.bind'="/plugintypes($tid)"};if($rows.Count-eq0){$cid=[string](Post customapis $body).customapiid}else{$cid=[string](One $rows $spec.uniqueName).customapiid;Patch customapis $cid $body}
    foreach($p in @($spec.requestParameters)){$rows=Rows "customapirequestparameters?`$select=customapirequestparameterid&`$filter=_customapiid_value eq $cid and uniquename eq '$(Esc $p.uniqueName)'";$b=@{uniquename=$p.uniqueName;name=$p.uniqueName;displayname=$p.displayName;type=[int]$p.type;isoptional=[bool]$p.isOptional;'CustomAPIId@odata.bind'="/customapis($cid)"};if($rows.Count-eq0){Post customapirequestparameters $b|Out-Null}else{Patch customapirequestparameters ([string](One $rows $p.uniqueName).customapirequestparameterid) $b}}
    foreach($p in @($manifest.responseProperties)){$rows=Rows "customapiresponseproperties?`$select=customapiresponsepropertyid&`$filter=_customapiid_value eq $cid and uniquename eq '$(Esc $p.uniqueName)'";$b=@{uniquename=$p.uniqueName;name=$p.uniqueName;displayname=$p.displayName;type=[int]$p.type;'CustomAPIId@odata.bind'="/customapis($cid)"};if($rows.Count-eq0){Post customapiresponseproperties $b|Out-Null}else{Patch customapiresponseproperties ([string](One $rows $p.uniqueName).customapiresponsepropertyid) $b}}
    $read=One (Rows "customapis?`$select=uniquename,_plugintypeid_value,isfunction,bindingtype&`$filter=customapiid eq $cid") $spec.uniqueName;if([string]$read._plugintypeid_value-ne$tid-or$read.isfunction-or$read.bindingtype-ne0){throw"Custom API readback failed for $($spec.uniqueName)."};Write-Host"PASS $($spec.uniqueName) customApiId=$cid"
  }
  Write-Host"PASS pluginTypeId=$tid assemblySha256=$dllHash manifestSha256=$manifestHash"
}finally{$token=$null}
