import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { resolve, relative, sep } from 'node:path';
import { GOVERNED_WRITES, LOCAL_ONLY_FLOWS, NOT_WIRED } from './platformInventory';

/**
 * Phase 106 — Outlook LIVE email mode release-readiness pin.
 *
 * No production code change ships with this phase. This single test
 * file is the entire deliverable beyond the docs. Its purpose is to
 * prove — at CI time — that operating `VITE_EMAIL_MODE=LIVE` is safe
 * for EXACTLY the two banker-triggered governed writes the
 * Phase 104 / Phase 105 swap landed:
 *
 *   - GOVERNED_WRITES.deal-document-request-email   (Phase 61 / 104)
 *   - GOVERNED_WRITES.deal-borrower-update-email    (Phase 105)
 *
 * Six invariants are pinned, each as a top-level describe block. If
 * any of these starts failing, the failure is a structural signal —
 * something has either accidentally expanded the LIVE send surface
 * (new method, new payload field, new caller, new automation
 * pathway) or accidentally regressed the honesty of the inventory.
 * Either is a release-readiness regression for LIVE mode.
 *
 * Sibling files used as the canonical references:
 *   - docs/PHASE_106_EMAIL_MODE_RELEASE_READINESS.md
 *   - docs/PHASE_104_OUTLOOK_LIVE_SEND.md
 *   - docs/PHASE_105_BORROWER_UPDATE_LIVE_SEND.md
 *   - src/deals/emailDelivery/outlookEmailAdapters.ts
 *   - src/deals/sendDocumentRequestEmail.ts
 *   - src/deals/sendBorrowerUpdateEmail.ts
 *   - src/shared/governance/platformInventory.ts
 */

const REPO_ROOT = resolve(__dirname, '..', '..', '..');

function readSource(rel: string): string {
  return readFileSync(resolve(REPO_ROOT, rel), 'utf8');
}

/**
 * Strips block and line comments before scanning. Necessary for the
 * "exactly one production file CALLS SendEmailV2" pin, because docs
 * comments in action files legitimately reference "SendEmailV2(...)"
 * as prose. Code is what matters; prose can describe.
 */
function stripComments(src: string): string {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, ' ')
    .replace(/(^|[^:])\/\/[^\n]*/g, '$1');
}

function relForward(abs: string): string {
  return relative(REPO_ROOT, abs).split(sep).join('/');
}

/**
 * Collects every .ts / .tsx file under a directory recursively,
 * EXCLUDING:
 *   - .test.ts / .test.tsx (test files are allowed to mock connector
 *     services, reference forbidden vocabulary in negation form, etc.)
 *   - src/generated/ (autogenerated SDK — must not be edited and
 *     legitimately exports every Outlook method the connector ships)
 */
function collectProductionSourceFiles(dirAbs: string, out: string[]): void {
  for (const entry of readdirSync(dirAbs)) {
    const abs = resolve(dirAbs, entry);
    const stat = statSync(abs);
    if (stat.isDirectory()) {
      if (relForward(abs).endsWith('src/generated')) continue;
      collectProductionSourceFiles(abs, out);
    } else if (
      stat.isFile() &&
      (entry.endsWith('.ts') || entry.endsWith('.tsx')) &&
      !entry.endsWith('.test.ts') &&
      !entry.endsWith('.test.tsx')
    ) {
      out.push(abs);
    }
  }
}

const PRODUCTION_SOURCE_FILES: readonly string[] = (() => {
  const out: string[] = [];
  collectProductionSourceFiles(resolve(REPO_ROOT, 'src'), out);
  return out;
})();

// The two governed writes that consume the LIVE Outlook adapter.
const LIVE_EMAIL_WRITE_IDS = [
  'deal-document-request-email',
  'deal-borrower-update-email',
] as const;

// The Phase 101 four summary-handoff source files. Each must stay
// copy-to-clipboard regardless of EMAIL_MODE.
const PHASE_101_HANDOFF_HELPER = 'src/shared/email/summaryOutlookHandoff.ts';
const PHASE_101_HANDOFF_BUTTONS = 'src/shared/email/SummaryOutlookHandoffButtons.tsx';
const PHASE_101_HANDOFF_CONSUMERS: readonly string[] = [
  'src/banker/BankerMorningCatchUp.tsx',
  'src/manager/ManagerMorningCatchUp.tsx',
  'src/deals/ActivityTimeline.tsx',
  'src/banker/RelationshipMemory.tsx',
];

// ---------------------------------------------------------------------------
// Invariant 1 — NOT_WIRED.email-delivery is absent
//
// Phase 105 retired the row when borrower-update email shipped LIVE.
// If this fails, either Phase 105 was reverted or someone re-added
// the row by hand — both would mis-represent capability state.
// ---------------------------------------------------------------------------

describe('Phase 106 — NOT_WIRED.email-delivery is absent', () => {
  it('NOT_WIRED contains no entry with id "email-delivery"', () => {
    const entry = NOT_WIRED.find((n) => n.id === 'email-delivery');
    expect(
      entry,
      'NOT_WIRED.email-delivery should have been retired in Phase 105 ' +
        'when the borrower-update LIVE send shipped. Its presence now would ' +
        'falsely claim borrower-update email is still local-only.',
    ).toBeUndefined();
  });

  it('NOT_WIRED contains no Outlook-connector-shaped row at all (Phase 104 + 105 closed every one)', () => {
    const ids = new Set(NOT_WIRED.map((n) => n.id));
    expect(ids.has('email-delivery')).toBe(false);
    expect(ids.has('outlook-connector-live-send')).toBe(false);
    expect(ids.has('outlook-send')).toBe(false);
    expect(ids.has('borrower-update-email')).toBe(false);
    expect(ids.has('document-request-email')).toBe(false);
  });

  it('no NOT_WIRED reason text describes the LIVE Outlook send as missing', () => {
    // Phase 106 honesty: the inventory's free-text reason fields must
    // not say "Outlook is not registered" or similar after the swap.
    for (const n of NOT_WIRED) {
      expect(
        n.reason,
        `NOT_WIRED.${n.id} reason should not claim the Outlook ` +
          'connector is unregistered — Phase 104 / 105 closed that.',
      ).not.toMatch(/outlook\s+connector\s+is\s+(?:not\s+yet\s+)?registered/i);
      expect(
        n.reason,
        `NOT_WIRED.${n.id} reason should not claim Outlook LIVE is missing.`,
      ).not.toMatch(/outlook\s+live\s+(?:is|remains)\s+(?:not\s+wired|missing|unwired)/i);
    }
  });
});

// ---------------------------------------------------------------------------
// Invariant 2 — ReleaseReadinessGate doesn't surface email-delivery
//
// The platformInventory data drives the gate's Capability Inventory
// section. With email-delivery retired, the row must not appear.
// We assert this at the data layer (the gate is a pure render of
// inventory + governance signals; the data-layer test is sufficient
// and avoids re-rendering the heavy admin component here).
// ---------------------------------------------------------------------------

describe('Phase 106 — ReleaseReadinessGate inventory no longer carries email-delivery as a blocker', () => {
  it('no NOT_WIRED entry has the "Borrower update email delivery" label', () => {
    const match = NOT_WIRED.find((n) =>
      /borrower\s+update\s+email\s+delivery/i.test(n.label),
    );
    expect(match).toBeUndefined();
  });

  it('no NOT_WIRED label contains "Outlook" + "delivery" / "email send"', () => {
    for (const n of NOT_WIRED) {
      expect(n.label).not.toMatch(/outlook.*email\s+delivery/i);
      expect(n.label).not.toMatch(/outlook.*live\s+send/i);
    }
  });

  it('the borrower-portal compound entry honestly acknowledges the Phase 104 / 105 swap', () => {
    // The borrower-portal row is the only place where "borrower email
    // delivery" still appears as a cross-reference, and only as a
    // truthful description of what IS wired (banker-initiated) vs
    // what is NOT (automation, inbound, portal).
    const bp = NOT_WIRED.find((n) => n.id === 'borrower-portal');
    expect(bp).toBeDefined();
    expect(bp!.reason).toMatch(/Phase\s+104.*document-request/i);
    // Note: the source text has a soft line-break artifact ("borrower- " +
    // "update"). Allow any whitespace between the hyphen and "update".
    expect(bp!.reason).toMatch(/Phase\s+105.*borrower[\s-]+update/i);
    // And explicitly pin that the row's remaining gap is automation
    // / inbound / portal — not the send path itself.
    expect(bp!.reason).toMatch(/no\s+automation/i);
    expect(bp!.reason).toMatch(/no\s+(?:scheduled|event[- ]driven|inbound)/i);
  });
});

// ---------------------------------------------------------------------------
// Invariant 3 — Outlook LIVE send is represented ONLY for two writes
//
// Two static-source signals:
//   (a) GOVERNED_WRITES contains exactly two ids that consume the
//       Outlook LIVE adapter, and they are the expected pair.
//   (b) exactly one production file imports Office365OutlookService,
//       and exactly one production file calls SendEmailV2 — the
//       adapter at src/deals/emailDelivery/outlookEmailAdapters.ts.
//   (c) getEmailAdapter() is consumed by EXACTLY the two action files.
// ---------------------------------------------------------------------------

describe('Phase 106 — Outlook LIVE send availability is bounded to two governed writes', () => {
  it('GOVERNED_WRITES contains both expected email send ids', () => {
    const ids = new Set(GOVERNED_WRITES.map((w) => w.id));
    for (const expected of LIVE_EMAIL_WRITE_IDS) {
      expect(
        ids.has(expected),
        `expected GOVERNED_WRITES to contain ${expected}`,
      ).toBe(true);
    }
  });

  it('GOVERNED_WRITES contains no other Outlook-send write surface', () => {
    // Any new id ending in "-email" that is not one of the two
    // expected writes would represent an unauthorized expansion.
    const otherEmailIds = GOVERNED_WRITES.filter((w) => w.id.endsWith('-email'))
      .map((w) => w.id)
      .filter((id) => !(LIVE_EMAIL_WRITE_IDS as readonly string[]).includes(id));
    expect(
      otherEmailIds,
      `Unexpected email governed writes: ${otherEmailIds.join(', ')}`,
    ).toEqual([]);
  });

  it('exactly one production source file imports Office365OutlookService', () => {
    const matches: string[] = [];
    for (const abs of PRODUCTION_SOURCE_FILES) {
      const rel = relForward(abs);
      if (rel.endsWith('emailLiveReleaseReadiness.test.ts')) continue;
      const src = readFileSync(abs, 'utf8');
      if (/from\s+['"][^'"]*Office365OutlookService['"]/.test(src)) {
        matches.push(rel);
      }
    }
    expect(matches).toEqual([
      'src/deals/emailDelivery/outlookEmailAdapters.ts',
    ]);
  });

  it('exactly one production source file calls Office365OutlookService.SendEmailV2(...) in CODE', () => {
    // Comments stripped — doc-prose in action files legitimately
    // references SendEmailV2; only code-level callsites count.
    const matches: string[] = [];
    for (const abs of PRODUCTION_SOURCE_FILES) {
      const rel = relForward(abs);
      if (rel.endsWith('emailLiveReleaseReadiness.test.ts')) continue;
      const src = stripComments(readFileSync(abs, 'utf8'));
      if (/Office365OutlookService\.SendEmailV2\s*\(/.test(src)) {
        matches.push(rel);
      }
    }
    expect(matches).toEqual([
      'src/deals/emailDelivery/outlookEmailAdapters.ts',
    ]);
  });

  it('no production source file calls any Office365OutlookService method OTHER than SendEmailV2 in CODE', () => {
    // The generated service exports calendar/contact/batch/subscription
    // methods. None of them must be referenced by production source.
    const forbiddenMethodPattern =
      /Office365OutlookService\.(?!SendEmailV2\b)[A-Za-z][A-Za-z0-9_]*\s*\(/g;
    const violations: string[] = [];
    for (const abs of PRODUCTION_SOURCE_FILES) {
      const rel = relForward(abs);
      if (rel.endsWith('emailLiveReleaseReadiness.test.ts')) continue;
      const src = stripComments(readFileSync(abs, 'utf8'));
      const hits = src.match(forbiddenMethodPattern);
      if (hits) {
        for (const h of hits) violations.push(`${rel}: ${h}`);
      }
    }
    expect(violations).toEqual([]);
  });

  it('getEmailAdapter() is consumed by exactly the two governed-write actions + the Phase 109 operator smoke helper', () => {
    // Phase 109 added one new caller — the operator-triggered smoke
    // test helper at src/admin/emailLiveSmokeTest.ts. The smoke
    // helper is NOT a governed write; it's an admin-only diagnostic
    // that reuses the SAME adapter so no new SendEmailV2 callsite is
    // introduced. The Phase 106 "exactly one production file imports
    // Office365OutlookService" + "exactly one production file calls
    // SendEmailV2 in CODE" pins remain unchanged.
    const callers: string[] = [];
    for (const abs of PRODUCTION_SOURCE_FILES) {
      const rel = relForward(abs);
      // The adapter file itself DEFINES the function; only count callers.
      if (rel === 'src/deals/emailDelivery/outlookEmailAdapters.ts') continue;
      if (rel.endsWith('emailLiveReleaseReadiness.test.ts')) continue;
      const src = readFileSync(abs, 'utf8');
      if (/\bgetEmailAdapter\s*\(/.test(src)) callers.push(rel);
    }
    expect(callers.sort()).toEqual(
      [
        'src/admin/emailLiveSmokeTest.ts',
        'src/deals/sendBorrowerUpdateEmail.ts',
        'src/deals/sendDocumentRequestEmail.ts',
      ].sort(),
    );
  });
});

// ---------------------------------------------------------------------------
// Invariant 4 — Phase 101 summary handoffs remain copy-to-clipboard
//
// The four summary handoff surfaces (Banker MorningCatchUp, Manager
// MorningCatchUp, ActivityTimeline, RelationshipMemory) MUST NOT
// import Office365OutlookService, MUST NOT call SendEmailV2, and the
// shared helper / button file pair MUST NOT either, REGARDLESS of
// EMAIL_MODE. They are deliberate copy-to-clipboard surfaces.
// ---------------------------------------------------------------------------

describe('Phase 106 — Phase 101 summary handoffs are copy-to-clipboard regardless of EMAIL_MODE', () => {
  for (const relPath of [
    PHASE_101_HANDOFF_HELPER,
    PHASE_101_HANDOFF_BUTTONS,
    ...PHASE_101_HANDOFF_CONSUMERS,
  ]) {
    it(`${relPath} does NOT import Office365OutlookService`, () => {
      const src = readSource(relPath);
      expect(src).not.toMatch(
        /from\s+['"][^'"]*Office365OutlookService['"]/,
      );
    });

    it(`${relPath} does NOT reference Office365OutlookService.SendEmailV2`, () => {
      const src = readSource(relPath);
      expect(src).not.toMatch(/Office365OutlookService\.SendEmailV2/);
    });

    it(`${relPath} does NOT call getEmailAdapter() or import the LIVE adapter`, () => {
      const src = readSource(relPath);
      expect(src).not.toMatch(/\bgetEmailAdapter\s*\(/);
      expect(src).not.toMatch(/\bliveAdapter\b/);
    });
  }

  it('the outlook-summary-handoff LOCAL_ONLY entry is still present and still says copy-to-clipboard', () => {
    const entry = LOCAL_ONLY_FLOWS.find(
      (f) => f.id === 'outlook-summary-handoff',
    );
    expect(entry).toBeDefined();
    expect(entry!.note).toMatch(/copy-to-clipboard/i);
    expect(entry!.note).toMatch(/regardless of EMAIL_MODE/i);
  });
});

// ---------------------------------------------------------------------------
// Invariant 5 — Borrower portal / automation / inbound / subscriptions
// remain honestly blocked and are NOT implied by LIVE email mode.
//
// We assert (a) the inventory still carries the borrower-portal
// compound block, (b) the production source contains no automation /
// scheduler / inbound / subscription wiring that would casually imply
// LIVE email = automated notifications, and (c) the borrower-portal
// reason text explicitly disclaims automation / inbound / portal.
// ---------------------------------------------------------------------------

describe('Phase 106 — borrower portal / automation / inbound / subscriptions remain honestly blocked', () => {
  it('NOT_WIRED.borrower-portal is still present with blockerKind: compound', () => {
    const entry = NOT_WIRED.find((n) => n.id === 'borrower-portal');
    expect(entry).toBeDefined();
    expect(entry!.blockerKind).toBe('compound');
  });

  it('borrower-portal reason explicitly disclaims automation / inbound / portal as still missing', () => {
    const entry = NOT_WIRED.find((n) => n.id === 'borrower-portal')!;
    expect(entry.reason).toMatch(/no\s+automation/i);
    expect(entry.reason).toMatch(/no\s+inbound[- ]mail\s+sync/i);
    expect(entry.reason).toMatch(/no\s+scheduled\s+trigger/i);
    expect(entry.reason).toMatch(/no\s+event[- ]driven\s+push/i);
  });

  it('no production source contains automation / scheduler / trigger / inbound-mail wiring', () => {
    // Phase 106 honesty pin: LIVE email DOES NOT imply any of these.
    // A scheduler or inbound-mail-poller landing without an explicit
    // governance phase would be a regression.
    const forbiddenPatterns: readonly RegExp[] = [
      /\b(setInterval|setTimeout)\s*\([^)]*sendBorrowerUpdateEmail/i,
      /\b(setInterval|setTimeout)\s*\([^)]*sendDocumentRequestEmail/i,
      /\bnew\s+CronJob\b/,
      /\bschedule\.scheduleJob\b/,
      /\bOnNewEmail\b/,
      /\bMailboxSubscription\b/,
      /\bSubscribeEmailUpdate\b/,
      /\bsubscribeWebhook\b/i,
    ];
    const violations: string[] = [];
    for (const abs of PRODUCTION_SOURCE_FILES) {
      const rel = relForward(abs);
      if (rel.endsWith('emailLiveReleaseReadiness.test.ts')) continue;
      const src = readFileSync(abs, 'utf8');
      for (const pat of forbiddenPatterns) {
        if (pat.test(src)) violations.push(`${rel} — matched ${pat}`);
      }
    }
    expect(violations).toEqual([]);
  });

  it('no production source imports a borrower-portal route / magic-link / invitation surface', () => {
    // Mirrors Phase 65's static-source guard, scoped to the Phase 106
    // honesty claim ("LIVE email does not imply borrower portal").
    const forbiddenImport =
      /from\s+['"][^'"]*\/(?:borrowerPortal|magicLink|invitationToken|borrowerInvite|borrowerAuth)['"]/i;
    const violations: string[] = [];
    for (const abs of PRODUCTION_SOURCE_FILES) {
      const rel = relForward(abs);
      const src = readFileSync(abs, 'utf8');
      if (forbiddenImport.test(src)) violations.push(rel);
    }
    expect(violations).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// Invariant 6 — no email payload expansion
//
// The two Outlook governed writes use ONLY: To, Subject, Body,
// Importance. Nothing else. The adapter's static source must not
// reference Attachments / Cc / Bcc / From / ReplyTo / Sensitivity /
// shared mailbox / Graph / calendar / inbound vocabulary in a way
// that would imply expansion.
// ---------------------------------------------------------------------------

describe('Phase 106 — no email payload expansion (To / Subject / Body / Importance only)', () => {
  const ADAPTER_FILE = 'src/deals/emailDelivery/outlookEmailAdapters.ts';
  const ACTION_FILES: readonly string[] = [
    'src/deals/sendDocumentRequestEmail.ts',
    'src/deals/sendBorrowerUpdateEmail.ts',
  ];

  it('the LIVE adapter sets EXACTLY the four expected ClientSendHtmlMessage fields', () => {
    const src = readSource(ADAPTER_FILE);
    // The payload literal in the LIVE adapter is the canonical site.
    // Pin the four field names appear; pin the forbidden field names
    // do not appear in the adapter source at all.
    expect(src).toMatch(/\bTo\s*:\s*input\.recipient\b/);
    expect(src).toMatch(/\bSubject\s*:\s*input\.subject\b/);
    expect(src).toMatch(/\bBody\s*:\s*input\.body\b/);
    expect(src).toMatch(/\bImportance\s*:\s*['"]Normal['"]/);
  });

  it('the LIVE adapter source does NOT reference forbidden ClientSendHtmlMessage fields', () => {
    const src = readSource(ADAPTER_FILE);
    const forbiddenFieldNames = [
      'Attachments',
      'Cc',
      'Bcc',
      'From',
      'ReplyTo',
      'Sensitivity',
    ] as const;
    for (const name of forbiddenFieldNames) {
      // We forbid the field name as a property key (followed by ':')
      // so we don't false-positive on words like "from" in prose.
      // Block-comment text is stripped to keep doc-prose honest
      // ("From: borrower@...") from tripping the pin.
      const stripped = src.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/(^|[^:])\/\/[^\n]*/g, '$1');
      const pattern = new RegExp(`\\b${name}\\b\\s*:`);
      expect(
        pattern.test(stripped),
        `Adapter source must not set a ${name} field on the payload`,
      ).toBe(false);
    }
  });

  it('the LIVE adapter source does NOT contain shared-mailbox / Graph / calendar / inbound vocabulary in code', () => {
    const src = readSource(ADAPTER_FILE);
    const stripped = src.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/(^|[^:])\/\/[^\n]*/g, '$1');
    // Forbidden code-level vocabulary. Each pattern targets a likely
    // API surface, not banker-facing prose.
    const forbiddenCodePatterns: readonly RegExp[] = [
      /\bsharedMailbox\b/i,
      /\bSendEmailFromShared/i,
      /\bmicrosoftGraph\b/i,
      /\bGraphClient\b/,
      /\bCalendar(?:Events?|Event)\b/,
      /\bGetEmails(?:V[0-9]+)?\b/,
      /\bOnNewEmail\b/,
      /\bGetMailTips\b/,
      /\bSubscribeMail(?:box)?\b/i,
    ];
    for (const pat of forbiddenCodePatterns) {
      expect(
        pat.test(stripped),
        `Adapter source must not reference ${pat} in code (shared-mailbox / Graph / calendar / inbound surface).`,
      ).toBe(false);
    }
  });

  it('each governed-write action passes ONLY recipient / subject / body / correlationId to the adapter', () => {
    // The adapter.send() call site in each action must reference
    // exactly these four fields. Anything else (e.g. attachments,
    // cc, bcc, from) would be a Phase 106 violation.
    for (const file of ACTION_FILES) {
      const src = readSource(file);
      // The adapter.send call sits inside the action's body. Pin the
      // four expected argument-object keys with a strict regex.
      expect(
        src,
        `${file} must call adapter.send with { recipient, subject, body, correlationId }`,
      ).toMatch(
        /adapter\.send\s*\(\s*\{\s*recipient\s*,\s*subject\s*:\s*input\.subject\s*,\s*body\s*:\s*input\.body\s*,\s*correlationId\s*,\s*\}\s*\)/,
      );
    }
  });

  it('neither action sets attachments / Cc / Bcc / From / ReplyTo / Sensitivity on its own payload', () => {
    for (const file of ACTION_FILES) {
      const src = readSource(file);
      const stripped = src
        .replace(/\/\*[\s\S]*?\*\//g, ' ')
        .replace(/(^|[^:])\/\/[^\n]*/g, '$1');
      for (const name of [
        'Attachments',
        'Cc',
        'Bcc',
        'ReplyTo',
        'Sensitivity',
      ] as const) {
        const pattern = new RegExp(`\\b${name}\\b\\s*:`);
        expect(
          pattern.test(stripped),
          `${file} must not set a ${name} field anywhere in its code.`,
        ).toBe(false);
      }
    }
  });

  it('the Outlook adapter does not claim delivery — "Outlook accepted" copy only', () => {
    // Phase 106 wording requirement: the LIVE adapter's user-facing
    // copy uses "accepted" semantics, never claims borrower delivery.
    // Match against the action layers (which produce the user-visible
    // timeline summary) and the adapter (which carries failure-mode
    // strings).
    for (const file of ['src/deals/sendDocumentRequestEmail.ts', 'src/deals/sendBorrowerUpdateEmail.ts']) {
      const src = readSource(file);
      // The success branch of describeSendOutcome MUST say "Outlook
      // accepted" (or equivalent acceptance wording) for the LIVE
      // path.
      expect(src).toMatch(/Outlook\s+(?:accepted|send\s+accepted|accepted\s+borrower\s+update|accepted\s+document\s+request)/i);
      // It MUST NOT positively claim delivery anywhere in the file.
      // Code-level check: forbid "delivered" / "was sent" / "has been
      // sent" / "email sent" as a positive substring.
      const stripped = src
        .replace(/\/\*[\s\S]*?\*\//g, ' ')
        .replace(/(^|[^:])\/\/[^\n]*/g, '$1');
      expect(
        /\bdelivered\b/i.test(stripped),
        `${file} must not contain the word "delivered" in code (claims of delivery are forbidden).`,
      ).toBe(false);
      expect(
        /\bemail\s+(?:was|has\s+been)\s+(?:sent|delivered)\b/i.test(stripped),
        `${file} must not claim the email "was sent" or "has been sent"/"delivered" (Outlook accepted only).`,
      ).toBe(false);
    }
  });
});
