import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  DOCUMENT_CHECKLIST_PILOT_UI_ENABLED,
  DOCUMENT_CHECKLIST_UI_GENERATE_ACTION_ENABLED,
} from '../../deals/documentChecklistPilotConfig';
import { DOCUMENT_CHECKLIST_GENERATION_ENABLED } from '../../deals/dealOriginationFeatureFlags';

/**
 * PHASE 190A — Power Platform generated-artifact build-recovery contract.
 *
 * Build-environment debt: a fresh clone cannot `pnpm build` because the
 * gitignored, local-only generated manifest `.power/schemas/appschemas/
 * dataSourcesInfo.ts` is absent, so `tsc -b` fails TS2307 across the generated
 * services + the two runtime readers. This phase restores fresh-clone build
 * determinism with a safe, offline, build-only fallback generated by a
 * preflight script and documented in a runbook. It enables nothing, writes
 * nothing to Dataverse, mutates no schema, and changes no checklist gate.
 *
 * These pins enforce: the runbook exists and says the right things; the
 * preflight script + emitted fallback are secret-free and mutation-free; the
 * generated services still import the manifest through the expected path; the
 * build is wired to self-heal; and all three checklist gates stay false.
 */

const ROOT = resolve(__dirname, '..', '..', '..');
const read = (rel: string) => readFileSync(resolve(ROOT, rel), 'utf8');

const DOC_REL = 'docs/PHASE_190A_POWER_PLATFORM_GENERATED_ARTIFACT_BUILD_RECOVERY.md';
const SCRIPT_REL = 'scripts/phase190A-power-artifact-preflight.mjs';
const MANIFEST_PATH = '.power/schemas/appschemas/dataSourcesInfo';

const DOC = read(DOC_REL);
const SCRIPT = read(SCRIPT_REL);
const PKG = read('package.json');
const POWER_CONFIG = read('power.config.json');
const CONFIG = read('src/deals/documentChecklistPilotConfig.ts');
const FLAGS = read('src/deals/dealOriginationFeatureFlags.ts');

/** A real Dataverse/tenant GUID, an http(s) URL, or a Windows/Unix user path. */
const GUID_RE = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i;
const URL_RE = /\bhttps?:\/\//i;
const USER_PATH_RE = /[A-Za-z]:\\Users\\|\/Users\/|\/home\//i;
/** A bearer/token/secret literal assignment (not the safety-prose words). */
const SECRET_LITERAL_RE =
  /(bearer\s+[A-Za-z0-9._-]{12,}|client_secret\s*[:=]|api[_-]?key\s*[:=]\s*['"][^'"]+|eyJ[A-Za-z0-9._-]{12,})/i;

// ---------------------------------------------------------------------------
// 1. The runbook exists and explains the failure + recovery.
// ---------------------------------------------------------------------------
describe('190A — runbook exists and documents the build recovery', () => {
  it('the Phase 190A doc exists on disk', () => {
    expect(existsSync(resolve(ROOT, DOC_REL))).toBe(true);
  });

  it('names the missing generated artifact path', () => {
    expect(DOC).toContain(MANIFEST_PATH);
  });

  it('explains the fresh-clone build failure and the recovery', () => {
    expect(DOC).toMatch(/fresh clone/i);
    expect(DOC).toMatch(/TS2307/);
    expect(DOC).toMatch(/tsc -b/);
    expect(DOC).toMatch(/build-only fallback/i);
    expect(DOC).toMatch(/pnpm power:schemas:ensure/);
    // Both failing import shapes are documented.
    expect(DOC).toContain('../../.power/schemas/appschemas/dataSourcesInfo');
    expect(DOC).toContain('../../../.power/schemas/appschemas/dataSourcesInfo');
  });

  it('warns not to commit secrets / tenant credentials and to keep .power gitignored', () => {
    expect(DOC).toMatch(/never commit `?\.power\/?`?/i);
    expect(DOC).toMatch(/no secrets|no.*tenant credentials|tenant.*credentials/i);
  });

  it('states no Dataverse writes and no schema mutation', () => {
    expect(DOC).toMatch(/no Dataverse writes/i);
    expect(DOC).toMatch(/no.*schema mutation/i);
  });

  it('records the operator verification commands', () => {
    expect(DOC).toMatch(/pnpm test --/);
    expect(DOC).toMatch(/phase190A/);
    expect(DOC).toMatch(/releaseCandidateSnapshot/);
    expect(DOC).toMatch(/phase188K/);
    expect(DOC).toMatch(/pnpm build/);
  });

  it('preserves the 188I/188J/188K disabled-gate posture in the doc', () => {
    expect(DOC).toMatch(/188I\s*\/\s*188J\s*\/\s*188K|188I\/188J\/188K/);
    expect(DOC).toMatch(/DOCUMENT_CHECKLIST_PILOT_UI_ENABLED\s*=\s*false/);
    expect(DOC).toMatch(/DOCUMENT_CHECKLIST_UI_GENERATE_ACTION_ENABLED\s*=\s*false/);
    expect(DOC).toMatch(/DOCUMENT_CHECKLIST_GENERATION_ENABLED\s*=\s*false/);
  });
});

// ---------------------------------------------------------------------------
// 2. The preflight script is mutation-free and secret-free.
// ---------------------------------------------------------------------------
describe('190A — preflight script is mutation-free and secret-free', () => {
  it('the preflight script exists on disk', () => {
    expect(existsSync(resolve(ROOT, SCRIPT_REL))).toBe(true);
  });

  it('contains no live-write HTTP verbs or schema-publish call', () => {
    for (const token of ['POST', 'PATCH', 'DELETE', 'PublishXml']) {
      expect(SCRIPT.includes(token)).toBe(false);
    }
  });

  it('makes no network call (no fetch / axios / node http client)', () => {
    expect(SCRIPT).not.toMatch(/\bfetch\s*\(/);
    expect(SCRIPT).not.toMatch(/\baxios\b/);
    expect(SCRIPT).not.toMatch(/require\(['"]https?['"]\)|from ['"]node:https?['"]/);
  });

  it('contains no URLs, GUIDs, secret literals, or local user paths', () => {
    expect(SCRIPT).not.toMatch(URL_RE);
    expect(SCRIPT).not.toMatch(GUID_RE);
    expect(SCRIPT).not.toMatch(SECRET_LITERAL_RE);
    expect(SCRIPT).not.toMatch(USER_PATH_RE);
  });

  it('derives its entries only from the tracked power.config.json native data sources', () => {
    expect(SCRIPT).toContain('power.config.json');
    expect(SCRIPT).toContain('databaseReferences');
    expect(SCRIPT).toMatch(/default\.cds/);
  });
});

// ---------------------------------------------------------------------------
// 3. The emitted fallback shape is native-only and secret-free.
//
// We assert against the script's emitted template (the only source of the
// fallback) and against every native name in power.config.json, which is the
// only runtime-injected content. Together these prove the produced file
// carries no URL/token/secret/tenant id/local path.
// ---------------------------------------------------------------------------
describe('190A — emitted build-only fallback is native + secret-free', () => {
  it('self-identifies as a build-only fallback', () => {
    expect(SCRIPT).toMatch(/BUILD-ONLY FALLBACK/);
  });

  it('emits only the minimal native entry shape (no connector apis / ids)', () => {
    expect(SCRIPT).toMatch(/"tableId":\s*"",/);
    expect(SCRIPT).toMatch(/"version":\s*"",/);
    expect(SCRIPT).toMatch(/"dataSourceType":\s*"Dataverse"/);
    expect(SCRIPT).toMatch(/"apis":\s*\{\}/);
    expect(SCRIPT).toContain('export const dataSourcesInfo');
  });

  it('every native power.config data source name is a safe schema identifier', () => {
    const config = JSON.parse(POWER_CONFIG) as {
      databaseReferences?: Record<string, { dataSources?: Record<string, { entitySetName?: string; logicalName?: string }> }>;
    };
    const sources = Object.values(config.databaseReferences?.['default.cds']?.dataSources ?? {});
    expect(sources.length).toBeGreaterThan(0);
    const safe = /^[a-z][a-z0-9_]*$/;
    for (const s of sources) {
      expect(s.entitySetName, `entitySetName ${s.entitySetName}`).toMatch(safe);
      expect(s.logicalName, `logicalName ${s.logicalName}`).toMatch(safe);
    }
  });
});

// ---------------------------------------------------------------------------
// 4. The build is wired to self-heal; generated services unchanged.
// ---------------------------------------------------------------------------
describe('190A — build wiring + generated services unchanged', () => {
  it('package.json runs the preflight ensure before tsc/vite build', () => {
    expect(PKG).toMatch(/"build":\s*"node scripts\/phase190A-power-artifact-preflight\.mjs --ensure && tsc -b && vite build"/);
    expect(PKG).toMatch(/"power:schemas:ensure":\s*"node scripts\/phase190A-power-artifact-preflight\.mjs --ensure"/);
    expect(PKG).toMatch(/"power:schemas:check":\s*"node scripts\/phase190A-power-artifact-preflight\.mjs --check"/);
  });

  it('generated services still import dataSourcesInfo through the expected path', () => {
    const svc = read('src/generated/services/Cr664_loandealsService.ts');
    expect(svc).toMatch(
      /import \{ dataSourcesInfo \} from '\.\.\/\.\.\/\.\.\/\.power\/schemas\/appschemas\/dataSourcesInfo'/,
    );
  });

  it('the two runtime readers still import dataSourcesInfo through the expected path', () => {
    for (const rel of [
      'src/deals/newDealReferenceRuntimeReader.ts',
      'src/deals/newDealAuditActorResolver.ts',
    ]) {
      expect(read(rel)).toContain("import('../../.power/schemas/appschemas/dataSourcesInfo')");
    }
  });
});

// ---------------------------------------------------------------------------
// 5. Build recovery changes no checklist gate (188I/188J/188K stay disabled).
// ---------------------------------------------------------------------------
describe('190A — checklist gates remain disabled', () => {
  it('the three runtime gates are false (constants)', () => {
    expect(DOCUMENT_CHECKLIST_PILOT_UI_ENABLED).toBe(false);
    expect(DOCUMENT_CHECKLIST_UI_GENERATE_ACTION_ENABLED).toBe(false);
    expect(DOCUMENT_CHECKLIST_GENERATION_ENABLED).toBe(false);
  });

  it('the three gates are still declared false in source', () => {
    expect(CONFIG).toMatch(/DOCUMENT_CHECKLIST_PILOT_UI_ENABLED = false as const/);
    expect(CONFIG).toMatch(/DOCUMENT_CHECKLIST_UI_GENERATE_ACTION_ENABLED = false as const/);
    expect(FLAGS).toMatch(/DOCUMENT_CHECKLIST_GENERATION_ENABLED = false as const/);
  });

  it('the 188I/188J/188K gate files still exist on disk', () => {
    for (const rel of [
      'src/shared/governance/phase188IUiEnableReadinessContract.test.ts',
      'src/shared/governance/phase188JControlledUiChecklistGenerationContract.test.ts',
      'src/shared/governance/phase188KUiChecklistGenerationCertificationContract.test.ts',
    ]) {
      expect(existsSync(resolve(ROOT, rel))).toBe(true);
    }
  });

  it('neither the preflight script nor the runbook flips any checklist gate to true', () => {
    for (const src of [SCRIPT, DOC]) {
      expect(src).not.toMatch(
        /DOCUMENT_CHECKLIST_(GENERATION_ENABLED|PILOT_UI_ENABLED|UI_GENERATE_ACTION_ENABLED)\s*=\s*true/,
      );
    }
  });
});
