// AUTO-GENERATED SEED (Phase 2). Hand-edit freely as subsystems route in Phase 3.
//
// Each entry is a source module deliberately NOT reachable from src/main.tsx yet.
// scripts/reachability-audit.mjs treats these as EXPECTED orphans; anything orphaned
// and NOT listed here is an UNEXPECTED orphan and fails the gate. As a subsystem is
// routed (Phase 3), delete its entries so the allow-list shrinks and the gate tightens.

export interface IntentionallyUnroutedModule {
  /** Repo-relative, forward-slashed path (matches reachability-audit output). */
  readonly path: string;
  /** Why it is unrouted today / how it becomes reachable. */
  readonly reason: string;
  /** The phase expected to route (or transitively reach) it. */
  readonly plannedPhase: string;
}

export const INTENTIONALLY_UNROUTED: readonly IntentionallyUnroutedModule[] = [
  // ── src/access ──
  { path: 'src/access/OperatorLaunchConsole.tsx', reason: 'Access/evidence/identity internals; reachable transitively via their consumers.', plannedPhase: 'Phase 3' },
  { path: 'src/access/adminEntitlementGrantAdapter.ts', reason: 'Access/evidence/identity internals; reachable transitively via their consumers.', plannedPhase: 'Phase 3' },
  { path: 'src/access/adminEntitlementRevokeAdapter.ts', reason: 'Access/evidence/identity internals; reachable transitively via their consumers.', plannedPhase: 'Phase 3' },
  { path: 'src/access/finalLaunchSmokeEvidence.ts', reason: 'Access/evidence/identity internals; reachable transitively via their consumers.', plannedPhase: 'Phase 3' },
  { path: 'src/access/finalLaunchSmokeEvidenceLoader.ts', reason: 'Access/evidence/identity internals; reachable transitively via their consumers.', plannedPhase: 'Phase 3' },
  { path: 'src/access/operatorLaunchConsoleModel.ts', reason: 'Access/evidence/identity internals; reachable transitively via their consumers.', plannedPhase: 'Phase 3' },
  { path: 'src/access/operatorSmokeEvidenceRegistry.ts', reason: 'Access/evidence/identity internals; reachable transitively via their consumers.', plannedPhase: 'Phase 3' },
  // ── src/activation ──
  { path: 'src/activation/adminEntitlementActivation.ts', reason: 'Activation/launch console internals; reachable once the admin activation surface routes.', plannedPhase: 'Phase 3' },
  { path: 'src/activation/borrowerCommsActivation.ts', reason: 'Activation/launch console internals; reachable once the admin activation surface routes.', plannedPhase: 'Phase 3' },
  { path: 'src/activation/checklistGenerationActivation.ts', reason: 'Activation/launch console internals; reachable once the admin activation surface routes.', plannedPhase: 'Phase 3' },
  { path: 'src/activation/crmActivation.ts', reason: 'Activation/launch console internals; reachable once the admin activation surface routes.', plannedPhase: 'Phase 3' },
  { path: 'src/activation/documentUploadActivation.ts', reason: 'Activation/launch console internals; reachable once the admin activation surface routes.', plannedPhase: 'Phase 3' },
  { path: 'src/activation/finalLaunchReadiness.ts', reason: 'Activation/launch console internals; reachable once the admin activation surface routes.', plannedPhase: 'Phase 3' },
  { path: 'src/activation/fullSystemActivation.ts', reason: 'Activation/launch console internals; reachable once the admin activation surface routes.', plannedPhase: 'Phase 3' },
  { path: 'src/activation/launchReadiness.ts', reason: 'Activation/launch console internals; reachable once the admin activation surface routes.', plannedPhase: 'Phase 3' },
  { path: 'src/activation/newDealCreateActivation.ts', reason: 'Activation/launch console internals; reachable once the admin activation surface routes.', plannedPhase: 'Phase 3' },
  { path: 'src/activation/portfolioBoardingActivation.ts', reason: 'Activation/launch console internals; reachable once the admin activation surface routes.', plannedPhase: 'Phase 3' },
  { path: 'src/activation/stageProgressionActivation.ts', reason: 'Activation/launch console internals; reachable once the admin activation surface routes.', plannedPhase: 'Phase 3' },
  // ── src/admin ──
  { path: 'src/admin/AdminEntitlementDiagnosticCard.tsx', reason: 'Admin internals (models/console pieces) reachable transitively via the admin surface.', plannedPhase: 'Phase 3' },
  { path: 'src/admin/checklistSignoffEvidence.ts', reason: 'Admin internals (models/console pieces) reachable transitively via the admin surface.', plannedPhase: 'Phase 3' },
  { path: 'src/admin/controlledLiveCutoverReadiness.ts', reason: 'Admin internals (models/console pieces) reachable transitively via the admin surface.', plannedPhase: 'Phase 3' },
  { path: 'src/admin/fullProductionLaunchEvidence.ts', reason: 'Admin internals (models/console pieces) reachable transitively via the admin surface.', plannedPhase: 'Phase 3' },
  { path: 'src/admin/outlookConnectorEvidence.ts', reason: 'Admin internals (models/console pieces) reachable transitively via the admin surface.', plannedPhase: 'Phase 3' },
  { path: 'src/admin/pacTableAccessEvidence.ts', reason: 'Admin internals (models/console pieces) reachable transitively via the admin surface.', plannedPhase: 'Phase 3' },
  { path: 'src/admin/runtimeVerifiedSchemaBridge.ts', reason: 'Admin internals (models/console pieces) reachable transitively via the admin surface.', plannedPhase: 'Phase 3' },
  // ── src/adminConfig ──
  { path: 'src/adminConfig/AdminConfigurationApplyPreviewPanel.tsx', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/AdminConfigurationPersistenceReadinessPanel.tsx', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/AdminConfigurationReviewQueuePanel.tsx', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/AdminConfigurationSummaryPanel.tsx', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/adminConfigurationApplyFeatureFlags.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/adminConfigurationApplyTypes.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/adminConfigurationContentSafety.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/adminConfigurationDataverseSchemaPlan.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/adminConfigurationPersistenceAdapter.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/adminConfigurationPersistenceFeatureFlags.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/adminConfigurationPersistenceMapper.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/adminConfigurationPersistenceTypes.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/adminConfigurationTransport.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/adminConfigurationTypes.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/buildAdminConfigurationApplyPlan.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/buildAdminConfigurationProposal.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/createAdminConfigurationControlledApplyEngine.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/createAdminConfigurationDataversePersistenceAdapter.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/createDisabledAdminConfigurationPersistenceAdapter.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/deriveAdminConfigurationApplyReadiness.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/deriveAdminConfigurationApplyWorkflow.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/deriveAdminConfigurationReviewDecision.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/deriveAdminConfigurationReviewQueue.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/deriveAdminConfigurationSchemaReadiness.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/resolveAdminConfigurationPersistenceAdapter.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/adminConfig/validateAdminConfigurationProposal.ts', reason: 'Admin configuration console (read-only preview) — built but not routed.', plannedPhase: 'Phase 3' },
  // ── src/annualReview ──
  { path: 'src/annualReview/AnnualReviewBorrowerRequestPanel.tsx', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/AnnualReviewFinancialCovenantPanel.tsx', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/AnnualReviewPackagePreviewPanel.tsx', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/annualReviewBorrowerRequestTypes.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/annualReviewDeliveryFeatureFlags.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/annualReviewDeliveryTypes.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/annualReviewEmailDeliveryAdapter.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/annualReviewFinancialFacts.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/annualReviewFinancialTypes.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/annualReviewPackageExportAdapter.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/annualReviewPackageTypes.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/annualReviewRequestFeatureFlags.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/annualReviewSmsDeliveryAdapter.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/annualReviewUploadLinkAdapter.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/buildAnnualReviewBoardPackage.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/buildAnnualReviewBorrowerRequestDraft.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/buildAnnualReviewBorrowerRequestPackage.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/buildAnnualReviewDeliveryAuditSummary.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/buildAnnualReviewEvidenceIndex.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/buildAnnualReviewFdicPackage.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/buildAnnualReviewFinancialMemoSections.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/buildAnnualReviewMemoPackage.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/deriveAnnualReviewBorrowerRequestWorkflow.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/deriveAnnualReviewFinancialAnalysisSnapshot.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/deriveAnnualReviewFinancialReadiness.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/deriveAnnualReviewFinancialSpreadSnapshot.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/deriveAnnualReviewPackageReadiness.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/deriveAnnualReviewPackageWorkflow.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/financialTestFixtures.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/packageTestFixtures.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/resolveAnnualReviewBorrowerRequestRecipients.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/resolveAnnualReviewCovenantDefinitions.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/resolveAnnualReviewDeliveryAdapters.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/testAnnualReviewCovenants.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/annualReview/validateAnnualReviewDeliveryRequest.ts', reason: 'Annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  // ── src/banker ──
  { path: 'src/banker/BankerCrmIntelligencePanel.tsx', reason: 'Banker sub-surface not yet routed.', plannedPhase: 'Phase 3' },
  // ── src/committee ──
  { path: 'src/committee/CreditCommitteePackageReviewQueuePanel.tsx', reason: 'Credit committee components — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/committee/CreditPackageExportPanel.tsx', reason: 'Credit committee components — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/committee/ESignEnvelopePanel.tsx', reason: 'Credit committee components — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/committee/creditCommitteePackageQueue.ts', reason: 'Credit committee components — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/committee/creditPackageExportAdapter.ts', reason: 'Credit committee components — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/committee/eSignEnvelopeAdapter.ts', reason: 'Credit committee components — built but not routed.', plannedPhase: 'Phase 3' },
  // ── src/copilot ──
  { path: 'src/copilot/copilotAuditLogger.ts', reason: 'Copilot extras — transport-gated; panels not routed standalone.', plannedPhase: 'Phase 3' },
  { path: 'src/copilot/copilotConnectorConfig.ts', reason: 'Copilot extras — transport-gated; panels not routed standalone.', plannedPhase: 'Phase 3' },
  { path: 'src/copilot/copilotCustomApiAdapter.ts', reason: 'Copilot extras — transport-gated; panels not routed standalone.', plannedPhase: 'Phase 3' },
  { path: 'src/copilot/copilotCustomApiContract.ts', reason: 'Copilot extras — transport-gated; panels not routed standalone.', plannedPhase: 'Phase 3' },
  { path: 'src/copilot/copilotDataverseCustomApiTransport.ts', reason: 'Copilot extras — transport-gated; panels not routed standalone.', plannedPhase: 'Phase 3' },
  { path: 'src/copilot/copilotLiveTransportHarness.ts', reason: 'Copilot extras — transport-gated; panels not routed standalone.', plannedPhase: 'Phase 3' },
  { path: 'src/copilot/copilotServerDeploymentReadiness.ts', reason: 'Copilot extras — transport-gated; panels not routed standalone.', plannedPhase: 'Phase 3' },
  { path: 'src/copilot/copilotServerHandler.ts', reason: 'Copilot extras — transport-gated; panels not routed standalone.', plannedPhase: 'Phase 3' },
  { path: 'src/copilot/copilotTransportReadiness.ts', reason: 'Copilot extras — transport-gated; panels not routed standalone.', plannedPhase: 'Phase 3' },
  // ── src/crm ──
  { path: 'src/crm/CrmAccountSurfaces.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/CrmActivityTimeline.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/CrmAdminControlPanel.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/CrmContactTaskBoard.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/CrmRelationshipCommandCenter.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/CrmRelationshipHealthCard.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/CrmRelationshipNetworkPanel.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/CrmRollupCards.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/CrmSpineReadinessConsole.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/CrmSpineRecoveryConsole.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/activityTimeline/CrmActivityTimelinePanel.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/activityTimeline/crmActivityTimelineModel.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/commandCenter/CrmCommandCenter.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/commandCenter/CrmCommandCenterShell.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/commandCenter/CrmRelationshipIntelligenceStory.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/commandCenter/CrmWorkspaceEntryCard.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/commandCenter/crmCommandCenterViewModel.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmAccountViewModel.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmActivityTaskModel.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmAdminControlModel.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmDataverseMapper.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmDataverseSchemaPlan.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmFullSchemaContract.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmLiveDataverseAdapter.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmLiveDataverseTransport.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmManagerTeamMountReadiness.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmPersistenceAdapter.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmPersistenceTypes.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmRelationshipHealthModel.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmRelationshipIdempotency.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmRelationshipRollups.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmRuntimeSchemaGate.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmSalesforceSpineApplyOrchestrator.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmSalesforceSpineAudit.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmSalesforceSpineLaunchReadiness.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmSalesforceSpineLiveGates.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmSalesforceSpineModel.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmSalesforceSpineNewDealLinkage.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmSalesforceSpinePersistenceAdapter.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmSalesforceSpineSchemaAdapter.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmSdkContract.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/crmWritebackAdapter.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/dailyActions/BankerCrmDailyActionQueue.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/dailyActions/bankerCrmDailyActionQueue.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/deriveCrmSchemaInspectionReport.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/deriveCrmSchemaSeedPlan.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/executiveStrategy/ExecutiveCrmStrategyView.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/executiveStrategy/executiveCrmStrategyViewModel.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/managerIntelligence/ManagerCrmPipelineIntelligence.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/managerIntelligence/managerCrmPipelineIntelligence.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/matching/crmEntityMatchingModel.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/ncinoLane/NcinoLane.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/ncinoLane/ncinoLaneViewModel.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/relationshipIntelligence/CrmRelationshipIntelligenceCockpit.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/relationshipIntelligence/crmRelationshipDrillThrough.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/relationshipIntelligence/crmRelationshipIntelligenceDrillthrough.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/relationshipIntelligence/crmRelationshipIntelligenceViewModel.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/resolveCrmPersistenceAdapter.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/salesforceLane/SalesforceLane.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/salesforceLane/salesforceLaneViewModel.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/sourceOfTruth/CrmSourceOfTruthCockpit.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/sourceOfTruth/crmSourceOfTruthCockpitViewModel.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/sourceOfTruth/crmSourceOfTruthMap.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/syncPreview/CrmSyncPreviewCockpit.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/syncPreview/crmSyncPreviewCockpitViewModel.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/syncPreview/crmSyncPreviewPlan.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/writeback/CrmDryRunWritebackCommandCenter.tsx', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/writeback/crmAllowlistedLiveWritePilot.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/writeback/crmControlledWritebackAdapter.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/writeback/crmDryRunWritebackCommandViewModel.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  { path: 'src/crm/writeback/crmWritebackPolicyGate.ts', reason: 'CRM relationship command center — built read surfaces not yet routed into a workspace.', plannedPhase: 'Phase 3' },
  // ── src/deals ──
  { path: 'src/deals/documentChecklistUiEnableReadiness.ts', reason: 'Deal sub-feature module not yet wired into DealRoute.', plannedPhase: 'Phase 3' },
  { path: 'src/deals/documentChecklistUiGenerationAction.ts', reason: 'Deal sub-feature module not yet wired into DealRoute.', plannedPhase: 'Phase 3' },
  { path: 'src/deals/newDealChecklistGenerationLiveDeps.ts', reason: 'Deal sub-feature module not yet wired into DealRoute.', plannedPhase: 'Phase 3' },
  // ── src/executive ──
  { path: 'src/executive/ProductProfitabilityAvailabilityPanel.tsx', reason: 'Executive workspace sub-surface not yet routed.', plannedPhase: 'Phase 3' },
  { path: 'src/executive/productProfitabilityAvailabilityModel.ts', reason: 'Executive workspace sub-surface not yet routed.', plannedPhase: 'Phase 3' },
  // ── src/generated ──
  { path: 'src/generated/index.ts', reason: 'Generated Dataverse service; becomes reachable transitively once a consuming subsystem routes.', plannedPhase: 'Phase 3' },
  { path: 'src/generated/models/Cr664_borrowersModel.ts', reason: 'Generated Dataverse service; becomes reachable transitively once a consuming subsystem routes.', plannedPhase: 'Phase 3' },
  { path: 'src/generated/models/Cr664_clientrelationshipsModel.ts', reason: 'Generated Dataverse service; becomes reachable transitively once a consuming subsystem routes.', plannedPhase: 'Phase 3' },
  { path: 'src/generated/models/Cr664_portfolioboardedloanevidencesModel.ts', reason: 'Generated Dataverse service; becomes reachable transitively once a consuming subsystem routes.', plannedPhase: 'Phase 3' },
  { path: 'src/generated/models/Cr664_teamsModel.ts', reason: 'Generated Dataverse service; becomes reachable transitively once a consuming subsystem routes.', plannedPhase: 'Phase 3' },
  { path: 'src/generated/models/Cr664_usersModel.ts', reason: 'Generated Dataverse service; becomes reachable transitively once a consuming subsystem routes.', plannedPhase: 'Phase 3' },
  { path: 'src/generated/services/Cr664_borrowersService.ts', reason: 'Generated Dataverse service; becomes reachable transitively once a consuming subsystem routes.', plannedPhase: 'Phase 3' },
  { path: 'src/generated/services/Cr664_clientrelationshipsService.ts', reason: 'Generated Dataverse service; becomes reachable transitively once a consuming subsystem routes.', plannedPhase: 'Phase 3' },
  { path: 'src/generated/services/Cr664_portfolioboardedloanevidencesService.ts', reason: 'Generated Dataverse service; becomes reachable transitively once a consuming subsystem routes.', plannedPhase: 'Phase 3' },
  { path: 'src/generated/services/Cr664_teamsService.ts', reason: 'Generated Dataverse service; becomes reachable transitively once a consuming subsystem routes.', plannedPhase: 'Phase 3' },
  { path: 'src/generated/services/Cr664_usersService.ts', reason: 'Generated Dataverse service; becomes reachable transitively once a consuming subsystem routes.', plannedPhase: 'Phase 3' },
  // ── src/integrations ──
  { path: 'src/integrations/IntegrationAdapterRegistryPanel.tsx', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/IntegrationRequestPreviewPanel.tsx', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/coreBanking/CoreBankingLookupPanel.tsx', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/coreBanking/coreBankingLookupAdapter.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/createDisabledIntegrationAdapters.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/deriveIntegrationReadiness.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/externalPlatforms/ExternalAllowlistedWritePilotPanel.tsx', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/externalPlatforms/ExternalDryRunWritebackPanel.tsx', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/externalPlatforms/ExternalEntityMatchReviewPanel.tsx', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/externalPlatforms/ExternalPlatformConnectorReadinessPanel.tsx', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/externalPlatforms/ExternalPlatformReadOnlyPanel.tsx', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/externalPlatforms/LiveExternalSyncPreviewPanel.tsx', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/externalPlatforms/externalAllowlistedWritePilot.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/externalPlatforms/externalDryRunWritebackPlan.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/externalPlatforms/externalEntityMatchAgainstLiveRecords.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/externalPlatforms/externalPlatformConnectorReadiness.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/externalPlatforms/externalPlatformReadOnlyAdapter.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/externalPlatforms/externalPlatformRecordMapper.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/externalPlatforms/externalWritebackSchemaValidator.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/externalPlatforms/liveExternalSyncPreview.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/integrationAdapterContracts.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/integrationAdapterTypes.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/integrationProviderRegistry.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/policyGates/AmlKycCreditBureauPolicyGatePanel.tsx', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/policyGates/amlKycCreditBureauPolicyGate.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/resolveIntegrationAdapter.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/integrations/validateIntegrationRequest.ts', reason: 'Core-banking / external integration registry + preview panels — built but not routed.', plannedPhase: 'Phase 3' },
  // ── src/navigation ──
  { path: 'src/navigation/workspaceScreens.ts', reason: 'Navigation metadata module reachable once consumed by the routed nav.', plannedPhase: 'Phase 3' },
  { path: 'src/navigation/intentionallyUnrouted.ts', reason: 'This allow-list itself: consumed by the reachability gate + its test, not by the app import graph. Intentionally never reachable from main.tsx.', plannedPhase: 'never' },
  // ── src/platform ──
  { path: 'src/platform/PlatformMetadataDashboard.tsx', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/PlatformObjectCatalogPanel.tsx', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/PlatformRelationshipMapPanel.tsx', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/PlatformViewCatalogPanel.tsx', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/ProductProcessTemplateCatalogPanel.tsx', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/ProductProcessTemplateSelectionPanel.tsx', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/derivePlatformObjectCatalog.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/derivePlatformObjectModel.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/derivePlatformObjectRelationshipMap.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/derivePlatformViewCatalog.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/derivePlatformViews.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/deriveProductProcessProfile.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/deriveProductProcessRequirements.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/deriveProductProcessTemplateReadiness.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/deriveProductProcessTemplateSelection.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/deriveWorkspaceCapabilityGroups.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/platformObjectModelTypes.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/platformObjectRegistry.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/platformSurfaceTypes.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/platformViewRegistry.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/productProcessMetadataTypes.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/productProcessRegistry.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/productProcessTemplateRegistry.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/platform/productProcessTemplateTypes.ts', reason: 'Platform metadata / catalog surfaces — built but not routed.', plannedPhase: 'Phase 3' },
  // ── src/portfolioAnnualReview ──
  { path: 'src/portfolioAnnualReview/AnnualPortfolioReviewCommandCenter.tsx', reason: 'Portfolio annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioAnnualReview/AnnualReviewCollectionQueue.tsx', reason: 'Portfolio annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioAnnualReview/AnnualReviewExceptionTape.tsx', reason: 'Portfolio annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioAnnualReview/AnnualReviewKpiRibbon.tsx', reason: 'Portfolio annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioAnnualReview/AnnualReviewLoanRow.tsx', reason: 'Portfolio annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioAnnualReview/AnnualReviewTaskBoard.tsx', reason: 'Portfolio annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioAnnualReview/BorrowerFinancialRequestPreview.tsx', reason: 'Portfolio annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioAnnualReview/annualReviewPersistenceAdapter.ts', reason: 'Portfolio annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioAnnualReview/annualReviewPersistenceTypes.ts', reason: 'Portfolio annual review subsystem — built but not routed.', plannedPhase: 'Phase 3' },
  // ── src/portfolioBoarding ──
  { path: 'src/portfolioBoarding/BoardLoanReviewPackagePreview.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/FdicBoardPackageWorkspace.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/FdicEvidenceIndex.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/FdicExaminerPackagePreview.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/FdicPackageSectionList.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioBoardingPackageExportModel.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingAuditPanel.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingCreateFlow.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingDetail.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingDocumentInventory.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingDocumentManager.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingDocumentUploadPanel.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingEditor.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingEvidenceManager.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingEvidencePanel.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingExaminerNotes.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingList.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingPreview.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingReadOnlySections.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingReadinessPanel.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingSaveBar.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingSearchPanel.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingStatusBanner.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingValidationSummary.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioLoanBoardingWorkspace.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/PortfolioManagerReviewPackagePreview.tsx', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/derivePortfolioBoardingSchemaInspectionReport.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/derivePortfolioBoardingSchemaSeedPlan.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/derivePortfolioBoardingSchemaVerificationReport.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/derivePortfolioLoanBoardingFormState.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/loadPortfolioBoardedLoansForWorkspace.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioBoardedLoanCommandCenterRows.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioBoardingAccess.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioBoardingCommandCenterAdapter.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioBoardingFeatureFlags.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioBoardingListRows.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioBoardingRuntimeSchemaGate.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioFullSchemaArtifact.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioLoanBoardingAuditTrail.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioLoanBoardingDataverseAdapter.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioLoanBoardingDataverseMapper.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioLoanBoardingDataverseSchemaPlan.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioLoanBoardingFormModel.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioLoanBoardingLiveDataverseTransport.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioLoanBoardingLivePersistence.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioLoanBoardingPersistenceTypes.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioLoanBoardingWriteAdapter.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioLoanDocumentUploadAdapter.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/portfolioRelationshipIdempotency.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/resolvePortfolioLoanBoardingAdapter.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/resolvePortfolioLoanBoardingPersistenceAdapter.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/usePortfolioLoanBoardingPersistence.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/portfolioBoarding/usePortfolioLoanDocumentPersistence.ts', reason: 'Portfolio (FDIC) loan boarding workspace — built but not routed.', plannedPhase: 'Phase 3' },
  // ── src/servicing ──
  { path: 'src/servicing/ServicingLifecycleMapperPanel.tsx', reason: 'Servicing components — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/servicing/ServicingLifecyclePanel.tsx', reason: 'Servicing components — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/servicing/deriveServicingCollateralSecurityStatus.ts', reason: 'Servicing components — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/servicing/deriveServicingCovenantReportingStatus.ts', reason: 'Servicing components — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/servicing/deriveServicingInsuranceTicklerStatus.ts', reason: 'Servicing components — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/servicing/deriveServicingLifecycleSnapshot.ts', reason: 'Servicing components — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/servicing/deriveServicingLifecycleStage.ts', reason: 'Servicing components — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/servicing/deriveServicingMaturityRenewalStatus.ts', reason: 'Servicing components — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/servicing/deriveServicingObligations.ts', reason: 'Servicing components — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/servicing/servicingLifecycleMapper.ts', reason: 'Servicing components — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/servicing/servicingLifecycleTypes.ts', reason: 'Servicing components — built but not routed.', plannedPhase: 'Phase 3' },
  // ── src/shared ──
  { path: 'src/shared/annualReview/annualReviewRequirementCatalog.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/annualReview/annualReviewTaskEngine.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/annualReview/annualReviewTypes.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/annualReview/deriveAnnualReviewCollectionPlan.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/annualReview/deriveAnnualReviewCommandCenterModel.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/annualReview/deriveAnnualReviewReadiness.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/annualReview/deriveBorrowerFinancialRequestPackage.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/annualReview/deriveBorrowerSoundnessAssessment.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/crm/crmDataverseSchemaPlan.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/crm/crmIntegrationSeams.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/crm/crmTypes.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/crm/deriveCrmContactTasks.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/crm/deriveCrmReadiness.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/crm/deriveCrmRelationshipNetworkSnapshot.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/crm/resolveBorrowerRequestRecipient.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/drillthrough/drillThroughRegistry.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/fdic/fdicEvidenceArchitecture.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/fdic/fdicRemediationArchitectureSnapshot.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/fdic/fdicRemediationOperatingModel.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/fdic/fdicRemediationRoadmap.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/fdic/fdicWorkspaceResponsibilityMap.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/portfolioBoarding/derivePortfolioLoanBoardingCompleteness.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/portfolioBoarding/fdicExaminerPackage.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/portfolioBoarding/portfolioLoanBoardingCatalog.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/portfolioBoarding/portfolioLoanBoardingSnapshot.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/portfolioBoarding/portfolioLoanBoardingTypes.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/portfolioBoarding/portfolioLoanDocumentCatalog.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/portfolioBoarding/portfolioLoanDocumentClassifier.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/portfolioBoarding/portfolioLoanDocumentReadiness.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  { path: 'src/shared/portfolioBoarding/portfolioLoanEvidenceBinder.ts', reason: 'Shared helper/model consumed by unrouted subsystems; becomes reachable transitively once its consumer routes.', plannedPhase: 'Phase 3' },
  // ── src/workflow ──
  { path: 'src/workflow/WorkflowRoutingPanel.tsx', reason: 'Workflow stage-gate panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/workflow/checklistWriteDependency.ts', reason: 'Workflow stage-gate panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/workflow/deriveConfigurableWorkflowRoute.ts', reason: 'Workflow stage-gate panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/workflow/deriveCreditCommitteeRoute.ts', reason: 'Workflow stage-gate panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/workflow/deriveWorkflowRoute.ts', reason: 'Workflow stage-gate panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/workflow/deriveWorkflowRoutingReadiness.ts', reason: 'Workflow stage-gate panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/workflow/deriveWorkflowStageSequence.ts', reason: 'Workflow stage-gate panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/workflow/stageAdvanceWriteDependency.ts', reason: 'Workflow stage-gate panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/workflow/workflowRouteRegistry.ts', reason: 'Workflow stage-gate panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/workflow/workflowRouteRuleRegistry.ts', reason: 'Workflow stage-gate panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/workflow/workflowRoutingConfigTypes.ts', reason: 'Workflow stage-gate panels — built but not routed.', plannedPhase: 'Phase 3' },
  { path: 'src/workflow/workflowRoutingTypes.ts', reason: 'Workflow stage-gate panels — built but not routed.', plannedPhase: 'Phase 3' },
  // ── src/workspaces ──
  { path: 'src/workspaces/WorkspaceShell.tsx', reason: 'Workspace sub-surface not yet routed.', plannedPhase: 'Phase 3' },
];

/** Set of allow-listed paths for O(1) membership checks. */
export const INTENTIONALLY_UNROUTED_PATHS: ReadonlySet<string> = new Set(
  INTENTIONALLY_UNROUTED.map((m) => m.path),
);
