import {describe,expect,it} from 'vitest';
import {authorizeTrustedActor,canonicalFingerprintMaterial,governedTargetPath,parseTransportResponse,sha256Hex,validateActivationRequest,POWER_AUTOMATE_ACTIVATION_CONTRACT_VERSION} from '../power-automate/activationContract.js';
const base={operation:'ensureFolder' as const,dealId:'11111111-1111-4111-8111-111111111111',correlationId:'correlation',idempotencyKey:'key',annualFolderName:'2026 Loans',folderName:'Borrower LLC'};
describe('Power Automate activation contract',()=>{
 it('derives a contained deterministic path and fingerprint',async()=>{expect(governedTargetPath(base)).toBe('/(a) Loans/2026 Loans/Borrower LLC');expect(await sha256Hex(canonicalFingerprintMaterial(base))).toMatch(/^[0-9a-f]{64}$/)});
 it('rejects caller authority and target overrides, invalid GUIDs, traversal, and incomplete uploads',()=>{expect(validateActivationRequest({...base,siteUrl:'https://evil',callerEmail:'x'})).toEqual(expect.arrayContaining(['CALLER_OVERRIDE_siteUrl','CALLER_OVERRIDE_callerEmail']));expect(validateActivationRequest({...base,dealId:'not-a-guid'})).toContain('INVALID_DEAL_ID');expect(validateActivationRequest({...base,folderName:'../escape'})).toContain('INVALID_FOLDERNAME');expect(validateActivationRequest({...base,operation:'upload'})).toContain('INCOMPLETE_UPLOAD')});
 it('authorizes only one active actor assigned to the deal',()=>{expect(authorizeTrustedActor({actorUpn:'a@bank.test',activePlatformUserCount:1,activeBankerIds:['B1'],dealExists:true,assignedBankerId:'b1'})).toEqual({authorized:true,bankerId:'B1'});expect(authorizeTrustedActor({activePlatformUserCount:1,activeBankerIds:['B1'],dealExists:true,assignedBankerId:'B1'})).toEqual({authorized:false,errorCode:'ACTOR_IDENTITY_CONTEXT_UNAVAILABLE'});expect(authorizeTrustedActor({actorUpn:'a',activePlatformUserCount:1,activeBankerIds:['B1'],dealExists:true,assignedBankerId:'B2'})).toEqual({authorized:false,errorCode:'DEAL_ACCESS_DENIED'})});
 it('rejects cross-deal, stale-contract, and incomplete responses',()=>{const ok={success:true,operation:base.operation,status:'COMPLETED',correlationId:base.correlationId,idempotencyKey:base.idempotencyKey,dealId:base.dealId,errorCode:'',errorMessage:'',fileMayExist:false,reconciliationRequired:false,targetPath:'/(a) Loans/2026 Loans/Borrower LLC',fileName:'',sharePointItemId:'1',sharePointUniqueId:'u',size:0,etag:'e',webUrl:'https://oldglory22.sharepoint.com/folder',created:true,completedOn:'2026-08-05T00:00:00Z',contractVersion:POWER_AUTOMATE_ACTIVATION_CONTRACT_VERSION};expect(parseTransportResponse(ok,base).success).toBe(true);expect(()=>parseTransportResponse({...ok,dealId:'22222222-2222-4222-8222-222222222222'},base)).toThrow('MALFORMED_RESPONSE');expect(()=>parseTransportResponse({...ok,webUrl:''},base)).toThrow('MALFORMED_RESPONSE')});
});
