// Shared entity/attribute definitions for the Factory Arc Phase 11
// closing-document-manifest table. Single source of truth for
// create/verify/rollback. NOT YET APPLIED to any live Dataverse
// environment -- this is a reviewed proposal only, mirroring the
// pr107-funding-authorization bundle's structure and helper functions
// exactly so create/verify/rollback stay consistent across migrations.
//
// Design note: GeneratedClosingDocumentManifest (src/closing/documents/
// closingDocumentTypes.ts) is an immutable, append-only history -- a deal
// can have many manifests over time via supersedesManifestId chains, and
// regeneration always creates a NEW row rather than mutating a prior one
// (see closingDocumentGeneration.ts's regenerateClosingDocument). That
// shape rules out an additive JSON column on cr664_loandeal the way PR105/
// PR106 modeled single-valued facts (financial spread inputs, risk rating
// inputs): a deal-level blob can only ever hold one value, never a growing
// history. This is modeled as its OWN table with a plain string dealId
// column (not yet a Lookup relationship -- see create-entity.mjs's closing
// note), matching the precedent pr107-funding-authorization already set
// for exactly the same "per-deal history" shape.
//
// The rendered document content itself is stored alongside its manifest
// row (cr664_renderedcontent) rather than in a separate table: each
// manifest is immutable and never mutated after creation, so there is no
// versioning concern a separate content table would solve, and keeping
// content next to its manifest means one row read reconstructs one
// document completely.

export const ENTITY_LOGICAL_NAME = 'cr664_closingdocumentmanifest';
export const ENTITY_DISPLAY_NAME = 'Closing Document Manifest';
export const ENTITY_PLURAL_DISPLAY_NAME = 'Closing Document Manifests';
export const PRIMARY_ATTRIBUTE_LOGICAL_NAME = 'cr664_manifestid';

// Columns beyond the primary id/name column, matching GeneratedClosingDocumentManifest's fields
// (src/closing/documents/closingDocumentTypes.ts) plus the rendered content itself.
export const COLUMNS = [
  { logicalName: 'cr664_dealid', displayName: 'Deal Id', attributeType: 'String', maxLength: 100 },
  { logicalName: 'cr664_templatekey', displayName: 'Template Key', attributeType: 'String', maxLength: 100 },
  { logicalName: 'cr664_templateversion', displayName: 'Template Version', attributeType: 'String', maxLength: 40 },
  { logicalName: 'cr664_generatedatiso', displayName: 'Generated At', attributeType: 'DateTime' },
  { logicalName: 'cr664_generatedbyactoremail', displayName: 'Generated By Actor Email', attributeType: 'String', maxLength: 320 },
  { logicalName: 'cr664_contenthash', displayName: 'Content Hash', attributeType: 'String', maxLength: 100 },
  { logicalName: 'cr664_correlationid', displayName: 'Correlation Id', attributeType: 'String', maxLength: 100 },
  { logicalName: 'cr664_status', displayName: 'Status', attributeType: 'String', maxLength: 40 },
  { logicalName: 'cr664_supersedesmanifestid', displayName: 'Supersedes Manifest Id', attributeType: 'String', maxLength: 100 },
  { logicalName: 'cr664_renderedcontent', displayName: 'Rendered Content', attributeType: 'Memo', maxLength: 1048576 },
];

export function requireEnv(name) {
  const v = process.env[name];
  if (!v || v.trim().length === 0) {
    console.error(`Missing required environment variable: ${name}`);
    process.exit(1);
  }
  return v;
}

export function apiBase(dataverseUrl) {
  return `${dataverseUrl.replace(/\/+$/, '')}/api/data/v9.2`;
}

export function authHeaders(accessToken) {
  return {
    Authorization: `Bearer ${accessToken}`,
    'OData-MaxVersion': '4.0',
    'OData-Version': '4.0',
    Accept: 'application/json',
    'Content-Type': 'application/json',
  };
}
