import {describe,expect,it,vi} from 'vitest';
import {createGeneratedPowerAutomateDocumentPort,createGeneratedPowerAutomateDryRunPort} from './dealSharePointPowerAutomateTransport';
import {POWER_AUTOMATE_ACTIVATION_CONTRACT_VERSION,type PowerAutomateTransportRequest} from '../../../microsoft365/sharepoint-transport/power-automate/activationContract';
const dealId='11111111-1111-4111-8111-111111111111';
const response=(request:PowerAutomateTransportRequest,extra:Record<string,unknown>={})=>({success:true,validationOnly:false,operation:request.operation,status:'COMPLETED',correlationId:request.correlationId,idempotencyKey:request.idempotencyKey,requestFingerprint:'a'.repeat(64),contentSha256:request.contentSha256??'',dealId:request.dealId,errorCode:'',errorMessage:'',fileMayExist:false,reconciliationRequired:false,targetPath:'/(a) Loans/2026 Loans/Borrower LLC',fileName:request.fileName??'',sharePointItemId:'item-1',sharePointUniqueId:'unique-1',size:request.expectedSize??0,etag:'etag',webUrl:'https://oldglory22.sharepoint.com/sites/BusinessLending/Documents/folder',created:true,completedOn:'2026-08-05T00:00:00Z',contractVersion:POWER_AUTOMATE_ACTIVATION_CONTRACT_VERSION,...extra});
const folderRequest={dealId,borrowerIdentity:'Borrower LLC',siteUrl:'https://oldglory22.sharepoint.com/sites/BusinessLending',libraryName:'Documents',annualFolderPath:'/(a) Loans/2026 Loans',companyFolderPath:'/(a) Loans/2026 Loans/Borrower LLC',actorSystemUserId:'actor',correlationId:'corr'};
describe('generated Power Automate document port',()=>{
 it('maps ensure, replay, and readback without inventing identifiers',async()=>{const run=vi.fn(async(request:PowerAutomateTransportRequest)=>response(request));const port=createGeneratedPowerAutomateDocumentPort({run});const first=await port.ensureFolder(folderRequest);const second=await port.ensureFolder(folderRequest);expect(first).toMatchObject({ok:true,created:true,folder:{folderItemId:'item-1'}});expect(second).toMatchObject({ok:true});expect(run.mock.calls[0][0].idempotencyKey).toBe(run.mock.calls[1][0].idempotencyKey)});
 it('fails closed for cross-deal and malformed responses',async()=>{const port=createGeneratedPowerAutomateDocumentPort({run:async(request)=>response(request,{dealId:'22222222-2222-4222-8222-222222222222'})});expect(await port.ensureFolder(folderRequest)).toMatchObject({ok:false,kind:'failed'})});
 it('reports partial upload failure as a possible orphan requiring reconciliation',async()=>{const port=createGeneratedPowerAutomateDocumentPort({run:async(request)=>response(request,{success:false,status:'FAILED',errorCode:'RECONCILIATION_REQUIRED',errorMessage:'Readback failed after create.',fileMayExist:true,reconciliationRequired:true,webUrl:''})});const ensured=createGeneratedPowerAutomateDocumentPort({run:async(request)=>response(request)});const folderResult=await ensured.ensureFolder(folderRequest);if(!folderResult.ok)throw new Error('setup');const result=await port.upload({folder:folderResult.folder,dealId,documentId:'doc',requirementIds:[],actorSystemUserId:'actor',correlationId:'corr',file:{originalFileName:'a.pdf',mimeType:'application/pdf',content:new Uint8Array([1,2,3])},storedFileName:'a.pdf'});expect(result).toMatchObject({ok:false,kind:'failed',fileMayExist:true})});
 it('rejects a non-governed configured target before invocation',async()=>{const run=vi.fn();const port=createGeneratedPowerAutomateDocumentPort({run});expect(await port.ensureFolder({...folderRequest,siteUrl:'https://other'})).toMatchObject({ok:false,kind:'configuration_required'});expect(run).not.toHaveBeenCalled()});
 it('maps DRY_RUN only to validation evidence and never to a folder identity',async()=>{const run=vi.fn(async(request:PowerAutomateTransportRequest)=>response(request,{success:false,validationOnly:true,status:'DRY_RUN_COMPLETED',sharePointItemId:'',sharePointUniqueId:'',etag:'',webUrl:'',created:false,errorMessage:'No write.'}));const dry=createGeneratedPowerAutomateDryRunPort({run});expect(await dry.validateFolder(folderRequest)).toMatchObject({ok:true,evidence:{validationOnly:true,targetPath:'/(a) Loans/2026 Loans/Borrower LLC'}});const live=createGeneratedPowerAutomateDocumentPort({run});expect(await live.ensureFolder(folderRequest)).toMatchObject({ok:false,kind:'configuration_required'})});
});
