/**
 * Phase 142H — Competitive gap deriver.
 *
 * PURE. Lists capability gaps versus reference platforms. Gaps are NOT failures:
 * most are intentionally disabled for governance. Every gap carries a reason, a
 * risk class, a safety blocker, a recommended FUTURE phase, and a prerequisite.
 * No recommendation bypasses a safety gate; nothing here enables anything.
 */

import type { CompetitiveGapSummary } from './executiveStrategyTypes';

const GAPS: readonly CompetitiveGapSummary[] = [
  { gapKey: 'live_admin_config_apply', title: 'Live admin configuration application', category: 'admin', reason: 'Admin configuration is review-only; proposals are never applied.', riskClass: 'runtime_write_disabled', safetyBlocker: 'No apply path; validForApply is always false (142G).', recommendedFuturePhase: 'Phase 142K — Admin configuration controlled apply workflow, no schema mutation', prerequisite: 'Controlled, review-gated apply workflow with audit logging.' },
  { gapKey: 'live_integration_transport', title: 'Live integration transport', category: 'integrations', reason: 'Integration providers are disabled by default; no transport is configured.', riskClass: 'external_integration_disabled', safetyBlocker: 'Live external calls are disabled in this phase (142F).', recommendedFuturePhase: 'Phase 142L — Integration transport proof-of-concept harness, fake transport only', prerequisite: 'Policy approval, vendor due diligence, and a reviewed transport adapter.' },
  { gapKey: 'live_borrower_outreach', title: 'Live borrower outreach', category: 'communications', reason: 'Borrower communications are preview / draft only; live sending is disabled.', riskClass: 'runtime_write_disabled', safetyBlocker: 'Sending stays disabled and approval-gated.', recommendedFuturePhase: 'Phase 142O — E-sign envelope adapter seam, disabled by default', prerequisite: 'Approval-gated send policy and DLP review.' },
  { gapKey: 'live_upload_link', title: 'Live upload-link generation', category: 'communications', reason: 'Upload-link generation remains behind a disabled adapter seam.', riskClass: 'runtime_write_disabled', safetyBlocker: 'Upload-link generation is disabled by default.', recommendedFuturePhase: 'Phase 142N — Live package export adapter seam, disabled by default', prerequisite: 'Secure link policy and human approval.' },
  { gapKey: 'final_package_export', title: 'Final package export', category: 'packages', reason: 'Packages are draft-only; there is no final export.', riskClass: 'runtime_write_disabled', safetyBlocker: 'Export stays draft-only (141P).', recommendedFuturePhase: 'Phase 142N — Live package export adapter seam, disabled by default', prerequisite: 'Reviewed export adapter and audit trail.' },
  { gapKey: 'esign_envelope', title: 'E-sign envelope integration', category: 'integrations', reason: 'E-sign is a future disabled seam; no envelope is sent.', riskClass: 'external_integration_disabled', safetyBlocker: 'No envelope send in this phase (142F).', recommendedFuturePhase: 'Phase 142O — E-sign envelope adapter seam, disabled by default', prerequisite: 'Vendor due diligence and approval-gated send.' },
  { gapKey: 'core_banking_sync', title: 'Core banking data sync', category: 'integrations', reason: 'Core banking is read-only metadata only; no write or live lookup.', riskClass: 'external_integration_disabled', safetyBlocker: 'No core write capability is enabled (142F).', recommendedFuturePhase: 'Phase 142P — Core banking read-only lookup adapter, disabled by default', prerequisite: 'Reviewed read-only transport and policy approval.' },
  { gapKey: 'credit_bureau_pull', title: 'Credit bureau pull', category: 'integrations', reason: 'No credit is pulled; bureau requires permissible purpose and approval.', riskClass: 'external_integration_disabled', safetyBlocker: 'Credit report data may not be transmitted in this phase (142F).', recommendedFuturePhase: 'Phase 142Q — AML/KYC and credit bureau policy gate, no live pull', prerequisite: 'Permissible purpose, human approval, and DLP review.' },
  { gapKey: 'aml_kyc_run', title: 'AML / KYC run', category: 'integrations', reason: 'No screening is executed; AML requires human approval.', riskClass: 'external_integration_disabled', safetyBlocker: 'No screening runs in this phase (142F).', recommendedFuturePhase: 'Phase 142Q — AML/KYC and credit bureau policy gate, no live pull', prerequisite: 'Human approval and PII transmission policy.' },
  { gapKey: 'servicing_transactions', title: 'Servicing transaction operations', category: 'servicing', reason: 'Servicing is read-only decision support; it posts no transactions.', riskClass: 'runtime_write_disabled', safetyBlocker: 'No payment posting, booking, or schedule mutation (142E).', recommendedFuturePhase: 'Phase 142R — Servicing lifecycle read-only Dataverse mapper', prerequisite: 'Reviewed read-only mapping and audit.' },
  { gapKey: 'accounting_payment_ops', title: 'Accounting / payment operations', category: 'servicing', reason: 'No accounting entries, payments, or disbursements occur.', riskClass: 'runtime_write_disabled', safetyBlocker: 'Money movement is forbidden in this phase.', recommendedFuturePhase: 'Phase 142R — Servicing lifecycle read-only Dataverse mapper', prerequisite: 'Core integration and reconciliation controls.' },
  { gapKey: 'production_permission_policy', title: 'Production permission policy testing', category: 'governance', reason: 'Permission policy changes are review-only; no widening.', riskClass: 'metadata_only', safetyBlocker: 'Permission widening is forbidden in this phase (142G).', recommendedFuturePhase: 'Phase 142K — Admin configuration controlled apply workflow, no schema mutation', prerequisite: 'Controlled permission review and audit.' },
  { gapKey: 'profitability_roe_analytics', title: 'Full product profitability / ROE analytics', category: 'analytics', reason: 'Profitability / ROE availability is not modeled yet.', riskClass: 'runtime_read', safetyBlocker: 'No operational financial data is fabricated.', recommendedFuturePhase: 'Phase 142S — Executive product profitability/ROE availability model', prerequisite: 'Governed availability model with no fabricated figures.' },
  { gapKey: 'live_workflow_mutation', title: 'Live workflow task / stage mutation', category: 'workflow', reason: 'Workflow routing is read-only decision support; no task or stage mutation.', riskClass: 'runtime_write_disabled', safetyBlocker: 'No task creation or stage change (142C).', recommendedFuturePhase: 'Phase 142M — Credit committee package review queue, no voting', prerequisite: 'Reviewed task adapter and approval gates.' },
];

export function deriveCompetitiveGaps(): readonly CompetitiveGapSummary[] {
  return GAPS;
}
